# -*- coding: utf-8 -*-
"""best_time_to_buy_and_sell_stock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qra-0sWt0otuQQpqBailEM2LwAEN5uU4
"""

class Solution(object):
    def maxProfit(self, prices):
        """
        :type prices: List[int]
        :rtype: int
        """

        maxDiff = 0
        minid = 0
        maxid = 0
        for idi, i in enumerate(prices):
            if i <= prices[minid]:
                minid = idi
            else:
                if i-prices[minid] > maxDiff:
                    maxDiff = i-prices[minid]
                    maxid = idi

        return maxDiff

soln = Solution()
someList = [7,6,4,3,1]
soln.maxProfit(someList)