# -*- coding: utf-8 -*-
"""Fibonacci_recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18LhuHCAMxJGEfUlGXWYhBmXb5MKJM52p
"""

class Solution(object):
    def fib(self, n):
        if n == 1 or n == 0:
            return n
        else:
            return self.fib(n-1) + self.fib(n-2)