# -*- coding: utf-8 -*-
"""length_of_last_word.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZIvxKe3uINuJ-LdQssAMcHxXuKQD8Z5O
"""

class Solution:
    def lengthOfLastWord(self, s: str):
        self.someLst = s.split()
        self.ranVar = self.someLst[-1: ]
        print(len(self.ranVar[0]))

class Solution:
    def lengthOfLastWord(self, s: str) -> int:
        self.someLst = s.split()
        self.ranVar = self.someLst[-1]
        return len(self.ranVar)