# -*- coding: utf-8 -*-
"""longest_common_prefix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e9sIDlgk4Hp4xbzfBFTuYSdUF931iBMp
"""

class Solution:
    def longestCommonPrefix(self, strs: list[str]) -> str:
      listOfStrings = strs
      smallestStr = min(listOfStrings, key = len)
      lcp = ''

      for idi, i in enumerate(smallestStr):
        for j in listOfStrings:
          if j[idi] == i:
            continue
          else:
            return lcp

        lcp += i
      return lcp