# -*- coding: utf-8 -*-
"""majority_element.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z-h1igDM7k29Q4izXPZaEQjvvTPD9lRn
"""

class Solution(object):
    def majorityElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        numsList = nums
        numsSet = set(numsList)
        dicct = {}

        for i in numsSet:
            dicct[i] = numsList.count(i)
        return max(dicct, key = dicct.get)

soln = Solution()
nums = [2,2,1,1,1,2,2]
soln.majorityElement(nums)