# -*- coding: utf-8 -*-
"""merge_sorted_array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ZS50rdN4KZOUbQJlzJK9fwP_EdrrFn2
"""

class Solution:
    def merge(self, nums1: list[int], m: int, nums2: list[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        while len(nums1) > m:
            nums1.pop(m)

        nums1.extend(nums2)
        nums1.sort()