# -*- coding: utf-8 -*-
"""PlusOne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iemYZDCFQFFamfPY-GlUSE-aPwfye1_9
"""

class Solution:
    def plusOne(self, digits):
        if (digits[len(digits) - 1] + 1) > 9:
            str1 = ''
            for i in digits:
               str1 += str(i)

            x = int(str1) + 1
            str2 = str(x)
            lista = []
            for i in str2:
                lista.append(int(i))

            return lista

        else:
            digits[len(digits) - 1]= digits[len(digits) - 1] + 1
            return digits