# -*- coding: utf-8 -*-
"""power_of_two_recursive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nu7k4KgwdVbh_nlDttNHr3VPK8gC4t4L
"""

class Solution(object):
    def isPowerOfTwo(self, n):
        """
        :type n: int
        :rtype: bool
        """
        if n == 1:
            return True
        elif n%2 != 0 or n == 0:
            return False
        else:
            return self.isPowerOfTwo(n/2)