# -*- coding: utf-8 -*-
"""power_of_four_recursive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tEzqqHM53NvMAbMPEjFHUYphzPr3u7Dm
"""

class Solution(object):
    def isPowerOfFour(self, n):
        """
        :type n: int
        :rtype: bool
        """


        if n == 1:
            return True
        elif n%4 != 0 or n == 0:
            return False
        else:
            return self.isPowerOfFour(n/4)

soln = Solution()
soln.isPowerOfFour(0)