# -*- coding: utf-8 -*-
"""power_of_three_recursive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AZJz3NnVpYX6LVayU7MyeNrHFvu5mO_w
"""

class Solution(object):
    def isPowerOfThree(self, n):
        """
        :type n: int
        :rtype: bool
        """
        if n == 1:
            return True
        elif n%3 != 0 or n == 0:
            return False
        else:
            return self.isPowerOfThree(n/3)