# -*- coding: utf-8 -*-
"""rotate_array_brute_force.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SfMI3tVHrfN7-mOaiESD2oez4uiC1DRl
"""

class Solution(object):
    def rotate(self, nums, k):
        """
        :type nums: List[int]
        :type k: int
        :rtype: None Do not return anything, modify nums in-place instead.
        """
        while k > 0:
            temPost = nums[len(nums)-1]
            i = 2
            while i <= len(nums):
                temp = nums[len(nums)-i]
                nums[len(nums)-i + 1] = temp
                i+=1
            nums[0] = temPost
            k-=1

        return nums